/*globals define, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Sat Dec 10 2022 20:36:09 GMT+0000 (Coordinated Universal Time).
 */

define([
    'js/Constants',
    'js/Utils/GMEConcepts',
    'js/NodePropertyNames'
], function (
    CONSTANTS,
    GMEConcepts,
    nodePropertyNames
) {

    'use strict';

    function VizXWControl(options) {

        this._logger = options.logger.fork('Control');

        this._client = options.client;

        // Initialize core collections and variables
        this._widget = options.widget;

        this._currentNodeId = null;
        this._currentNodeParentId = undefined;

        this._initWidgetEventHandlers();

        this._logger.debug('ctor finished');
    }

    VizXWControl.prototype._initWidgetEventHandlers = function () {
        this._widget.onNodeClick = function (id) {
            // Change the current active object
            WebGMEGlobal.State.registerActiveObject(id);
        };
    };

    /* * * * * * * * Visualizer content update callbacks * * * * * * * */
    // One major concept here is with managing the territory. The territory
    // defines the parts of the project that the visualizer is interested in
    // (this allows the browser to then only load those relevant parts).
    VizXWControl.prototype.selectedObjectChanged = function (nodeId) {
        var desc = this._getObjectDescriptor(nodeId),
            self = this;

        self._logger.debug('activeObject nodeId \'' + nodeId + '\'');

        // Remove current territory patterns
        if (self._currentNodeId) {
            self._client.removeUI(self._territoryId);
        }

        self._currentNodeId = nodeId;
        self._currentNodeParentId = undefined;

        if (typeof self._currentNodeId === 'string') {
            // Put new node's info into territory rules
            self._selfPatterns = {};
            self._selfPatterns[nodeId] = {children: 0};  // Territory "rule"

            self._widget.setTitle(desc.name.toUpperCase());

            if (typeof desc.parentId === 'string') {
                self.$btnModelHierarchyUp.show();
            } else {
                self.$btnModelHierarchyUp.hide();
            }

            self._currentNodeParentId = desc.parentId;

            self._territoryId = self._client.addUI(self, function (events) {
                self._eventCallback(events);
            });

            // Update the territory
            self._client.updateTerritory(self._territoryId, self._selfPatterns);

            self._selfPatterns[nodeId] = {children: 1};
            self._client.updateTerritory(self._territoryId, self._selfPatterns);
        }
    };

    // This next function retrieves the relevant node information for the widget
    VizXWControl.prototype._getObjectDescriptor = function (nodeId) {
        var node = this._client.getNode(nodeId),
            objDescriptor;
        if (node) {
            objDescriptor = {
                id: node.getId(),
                name: node.getAttribute(nodePropertyNames.Attributes.name),
                childrenIds: node.getChildrenIds(),
                parentId: node.getParentId(),
                isConnection: GMEConcepts.isConnection(nodeId)
            };
        }

        return objDescriptor;
    };

    /* * * * * * * * Node Event Handling * * * * * * * */
    VizXWControl.prototype._eventCallback = function (events) {
        var i = events ? events.length : 0,
            event;

        this._logger.debug('_eventCallback \'' + i + '\' items');

        while (i--) {
            event = events[i];
            switch (event.etype) {

            case CONSTANTS.TERRITORY_EVENT_LOAD:
                this._onLoad(event.eid);
                break;
            case CONSTANTS.TERRITORY_EVENT_UPDATE:
                this._onUpdate(event.eid);
                break;
            case CONSTANTS.TERRITORY_EVENT_UNLOAD:
                this._onUnload(event.eid);
                break;
            default:
                break;
            }
        }

        this._logger.debug('_eventCallback \'' + events.length + '\' items - DONE');
    };

    VizXWControl.prototype._onLoad = function (gmeId) {
        var description = this._getObjectDescriptor(gmeId);
        this._widget.addNode(description);
    };

    VizXWControl.prototype._onUpdate = function (gmeId) {
        var description = this._getObjectDescriptor(gmeId);
        this._widget.updateNode(description);
    };

    VizXWControl.prototype._onUnload = function (gmeId) {
        this._widget.removeNode(gmeId);
    };

    VizXWControl.prototype._stateActiveObjectChanged = function (model, activeObjectId) {
        if (this._currentNodeId === activeObjectId) {
            // The same node selected as before - do not trigger
        } else {
            this.selectedObjectChanged(activeObjectId);
        }
    };

      /* * * * * * * * Machine manipulation functions * * * * * * * */
      /* * * * * * * * reference: https://github.com/austinjhunt/petrinet-webgme-designstudio/blob/main/petri-net/src/visualizers/panels/SimViz/SimVizControl.js * * * * * * * */
    VizXWControl.prototype._initPetriNet = function () {
        const rawMETA = this._client.getAllMetaNodes();
        const META = {};
        const self = this;
        rawMETA.forEach((node) => {
            META[node.getAttribute("name")] = node.getId(); //we just need the id...
        });
        const petriNetNode = this._client.getNode(this._currentNodeId);
        const elementIds = petriNetNode.getChildrenIds();
        let placeIds = getPlacesIds(this._client, elementIds);
        let transitionIds = getTransitionsIds(this._client, elementIds);
        let arcsTransitionToPlace = getArcs(
            self._client,
            "ArcTransitionToPlace",
            elementIds
        );
        let arcsPlaceToTransition = getArcs(
            self._client,
            "ArcPlaceToTransition",
            elementIds
        );
        let inputMatrix = getInputMatrix(
            placeIds,
            transitionIds,
            arcsTransitionToPlace
        );
        let startingPlaceId = getStartingPlaceId(inputMatrix);
        let outputMatrix = getOutputMatrix(
            placeIds,
            transitionIds,
            arcsPlaceToTransition
        );
        let petriNet = {
            /* functions to pass logic to widget */
            deadlockActive: _petriNetInDeadlock,
            /* end functions */
            startingPlace: startingPlaceId,
            places: {},
            transitions: {},
            inputMatrix: inputMatrix,
            outputMatrix: outputMatrix,
            arcsPlaceToTransition: arcsPlaceToTransition,
            arcsTransitionToPlace: arcsTransitionToPlace,
        };
        elementIds.forEach((elementId) => {
            const node = self._client.getNode(elementId);
            if (node.isTypeOf(META["Place"])) {
                petriNet.places[elementId] = {
                id: elementId,
                name: node.getAttribute("name"),
                currentMarking: parseInt(node.getAttribute("currentMarking")),
                nextPlaceIds: getNextPlacesFromCurrentPlace(
                    elementId,
                    arcsPlaceToTransition,
                    arcsTransitionToPlace
                ),
                outTransitions: getOutTransitionsFromPlace(elementId, outputMatrix),
                inTransitions: getInTransitionsToPlace(elementId, inputMatrix),
                outArcs: getOutArcsFromPlace(elementId, arcsPlaceToTransition),
                position: node.getRegistry("position"),
            };
        } else if (node.isTypeOf(META["Transition"])) {
            petriNet.transitions[elementId] = {
                id: elementId,
                name: node.getAttribute("name"),
                outPlaces: getOutPlacesFromTransition(elementId, inputMatrix),
                inPlaces: getInPlacesToTransition(elementId, outputMatrix),
                outArcs: getOutArcsFromTransition(elementId, arcsTransitionToPlace),
                position: node.getRegistry("position"),
                };
            }
        });
        petriNet.setFireableEvents = this.setFireableEvents;
        self._widget.initMachine(petriNet);
    };

    VizXWControl.prototype.clearPetriNet = function () {
        this._networkRootLoaded = false;
        this._widget.destroyMachine();
    };

    VizXWControl.prototype.setFireableEvents = function (enabledTransitions) {
        this._fireableEvents = enabledTransitions;
        if (enabledTransitions && enabledTransitions.length >= 1) {
            // fill dropdown button with options. only including enabled transitions
            this.$btnEventSelector.clear();
            enabledTransitions.forEach((transition) => {
                this.$btnEventSelector.addButton({
                text: `Fire enabled transition ${transition.name}`,
                title: `Fire enabled transition ${transition.name}`,
                data: { event: transition },
                clickFn: (data) => {
                    this._widget.fireEvent(data.event);
                    },
                });
            });
        } else if (enabledTransitions && enabledTransitions.length === 0) {
            this._fireableEvents = null;
            }
        this._displayToolbarItems();
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    VizXWControl.prototype.destroy = function () {
        this._detachClientEventListeners();
        this._removeToolbarItems();
    };

    VizXWControl.prototype._attachClientEventListeners = function () {
        this._detachClientEventListeners();
        WebGMEGlobal.State.on('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged, this);
    };

    VizXWControl.prototype._detachClientEventListeners = function () {
        WebGMEGlobal.State.off('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged);
    };

    VizXWControl.prototype.onActivate = function () {
        this._attachClientEventListeners();
        this._displayToolbarItems();

        if (typeof this._currentNodeId === 'string') {
            WebGMEGlobal.State.registerActiveObject(this._currentNodeId, {suppressVisualizerFromNode: true});
        }
    };

    VizXWControl.prototype.onDeactivate = function () {
        this._detachClientEventListeners();
        this._hideToolbarItems();
    };

    /* * * * * * * * * * Updating the toolbar * * * * * * * * * */
    VizXWControl.prototype._displayToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].show();
            }
        } else {
            this._initializeToolbar();
        }
    };

    VizXWControl.prototype._hideToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].hide();
            }
        }
    };

    VizXWControl.prototype._removeToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].destroy();
            }
        }
    };

    VizXWControl.prototype._initializeToolbar = function () {
        var self = this,
            toolBar = WebGMEGlobal.Toolbar;

        this._toolbarItems = [];

        this._toolbarItems.push(toolBar.addSeparator());

        /************** Go to hierarchical parent button ****************/
        this.$btnModelHierarchyUp = toolBar.addButton({
            title: 'Go to parent',
            icon: 'glyphicon glyphicon-circle-arrow-up',
            clickFn: function (/*data*/) {
                WebGMEGlobal.State.registerActiveObject(self._currentNodeParentId);
            }
        });
        this._toolbarItems.push(this.$btnModelHierarchyUp);
        this.$btnModelHierarchyUp.hide();

        /************** Checkbox example *******************/

        this.$cbShowConnection = toolBar.addCheckBox({
            title: 'toggle checkbox',
            icon: 'gme icon-gme_diagonal-arrow',
            checkChangedFn: function (data, checked) {
                self._logger.debug('Checkbox has been clicked!');
            }
        });
        this._toolbarItems.push(this.$cbShowConnection);

        this._toolbarInitialized = true;
    };

    return VizXWControl;
});
